{
	"version": 1698474313,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/Adventure game/player_stand-sheet0.png",
		"images/Adventure game/player_stand-sheet1.png",
		"images/Adventure game/player_stand-sheet2.png",
		"images/Adventure game/sky500p-sheet0.png",
		"images/Adventure game/tilegreen-sheet0.png",
		"images/Adventure game/level-sheet0.png",
		"images/Adventure game/selamat-sheet0.png",
		"images/Adventure game/newbackground1920x-sheet0.png",
		"images/Adventure game/enemyflying_-sheet0.png",
		"images/Adventure game/level2-sheet0.png",
		"images/Adventure game/roadtexture_-sheet0.png",
		"images/Adventure game/sprite-sheet0.png",
		"images/Adventure game/pngtreepinkhousedooropenclipartpngimage_-sheet0.png",
		"images/Adventure game/istockphoto1397249356612x612removebgpreview-sheet0.png",
		"images/Adventure game/th-sheet0.png",
		"images/Adventure game/awan-sheet0.png",
		"images/Adventure game/pesawat-sheet0.png",
		"images/Adventure game/flaggreen_up-sheet0.png",
		"images/Adventure game/flagred_up-sheet0.png",
		"images/Adventure game/hills_1500p-sheet0.png",
		"images/Adventure game/hills_2500p-sheet0.png",
		"images/Adventure game/tilegreen_-sheet0.png",
		"images/Adventure game/playerred_stand-sheet0.png",
		"images/Adventure game/kotakmerah-sheet0.png",
		"images/Adventure game/kotakhijau-sheet0.png",
		"media/Adventure game/enemyhit.m4a",
		"media/Adventure game/enemyhit.ogg",
		"media/Adventure game/kalah.m4a",
		"media/Adventure game/kalah.ogg",
		"media/Adventure game/bounce.m4a",
		"media/Adventure game/bounce.ogg",
		"media/Adventure game/menang.m4a",
		"media/Adventure game/menang.ogg",
		"media/Adventure game/explosion.m4a",
		"media/Adventure game/explosion.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}